### PR TITLE
French translation & Name and color coding adjust

### LINKED ISSUE #10: Harvest Level 0 doesn't show
I have 2 problems

-first harvest level 0 don't appear
-~~second the reported harvest level are wrong~~

(we can mine stone with wood or gold)

(we can mine iron with stone)

(we can mine diamond with iron)

(we can mine ancient debris with diamond)

(and with netherite we should be able to mine the next thing but i'm in vanilla so the next thing doesn't exist)

i will make a PR to fix this as i translate in french.

### PR DESCRIPTION
**Pull request by Julienraptor01**
Well i don't know why but the name of harvest level were wrong.
This fixes #10 for the wrong level part

### CODE REVIEW

**Comment by shedaniel** [comment]
No, that's not how it works, the levels are the effective same level of blocks it can mine, like level 0 can mine wood, 1 can mine iron, not that 0 is made of wood.

**Comment by Julienraptor01** [comment]
A block that has an harvest level of 0 need at minimum a wooden tool to be broken, a block with an harvest level of 1 need at minimum a stone tool to be broken, etc. What you say is right but you can go lower. You don't need diamond to mine diamond, you can do it with iron.

**Comment by shedaniel** [comment]
You don't need diamond to mine diamond, you need a level 2 tool (iron-level tool) to mine diamond

**Comment by Julienraptor01** [comment]
> You don't need diamond to mine diamond, you need a level 2 tool (iron-level tool) to mine diamond

It's literally what i said

**Comment by Julienraptor01** [comment]
How can i build this mod by myself ? Pls

**Comment by Julienraptor01** [comment]
> You don't need diamond to mine diamond, you need a level 2 tool (iron-level tool) to mine diamond

Well because i was nearly sure of what i was saying i decided to make a google research either to make me see that I'm wrong ot that I'm right. Here's what i found when searching "minecraft wiki harvest level"

https://minecraftmodcustomstuff.fandom.com/wiki/HarvestLevel
https://mcreator.net/wiki/harvest-level
https://mcreator.fandom.com/wiki/Harvest_level
https://wiki.aidancbrady.com/wiki/Tools

Si either all these sites are wrong or maybe you misunderstood something

And btw you say yourself level 2 is iron but in the en_us level 2 is named diamond and that can be seen on my 3rd screenshot in the issue that i created. On my 3rd screenshot i look at a diamond ore which is supposed to show me that i need a level 2 iron tool to mine it but it says diamond(2).

**Comment by shedaniel** [comment]
You are misunderstanding, the level displayed in this mod is not the equivalent tool tier, it is the equivalent block hardness. Say you are looking at Coal Ore, its level is equivalent to that of Stone.

**Comment by Julienraptor01** [comment]
OK i misunderstood but what you said wasn't clear so i have some idea to resolve that problem. Could there be a setting to show tool level instead of block level. It would allow people to use the option they understand.

**Pull request closed without merging**
